name: projek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^0.6.3
  flutter:
    sdk: flutter
  get: 4.6.6
  http: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true
